name: Deploy to prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: sevria/actions/.github/workflows/deploy-cloudflare-workers.yaml@main
    secrets: inherit
    with:
      environment: prod
