name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: sevria/actions/.github/workflows/publish-npm-package.yaml@main
    secrets: inherit
